### ISSUE TITLE
CBK HOSTED KNET & T-PAY PAYMENT GATEWAY

### ISSUE THREAD

**Issue by aqeelhashem** [asciisd/knet#10]
Hello E.aemadin.

I hope every thing is fine, 

i have a customer which he subscribe with (CBK HOSTED KNET & T-PAY PAYMENT GATEWAY)

so, is this package support this kind of payment gateway ?

if not , Do you know where to find the right package, even if it is paid?

this is the Integration Guide

[guide](https://pg.cbk.com/manage/Docs/CBK%20HOSTED%20KNET%20&%20T-PAY%20PAYMENT%20GATEWAY-Integration%20&%20Reference%20Manual.pdf)

**Comment by aemaddin** [comment]
Hi @aqeelhashem,

Sorry for the delay. I think this guide does not use the same endpoints. You can fork this package and modify it to fit your integration. In the end, they all use the same architecture.

**Comment by aemaddin** [comment]
Hi Aqeel,

This package works with all KNET integrations V2, for your information, all KNET networks work with the same endpoint, so there are no differences between an endpoint on different banks.

Thanks & Best regards
