### ISSUE TITLE
open ssl issue

### ISSUE THREAD

**Issue by osamaO0** [asciisd/knet#11]
i am trying to use default example for pay method in my controller and get this error any suggestion?

**Comment by aemaddin** [comment]
Hello @osamaO0 

Did you use this package in testing mode or production mode? If you are in production mode, I think the issue is with the SSL Certificate on your server. A secure connection during production is required.

**Comment by osamaO0** [comment]
@aemaddin thanks for reply but ssl is enabled

here is my code 

public function bill(Request $request) {

    	try{
            $payment = $request->user()->pay($request->amount, [
                'udf1' => $request->name,
                'udf2' => $request->email
            ]);
        } catch(\Asciisd\Knet\Exceptions\PaymentActionRequired $exception) {
            // do whatever you want with this 
            $payment = $exception->payment;
        } finally {
            // redirect user to payment url to complete the payment
            return $payment->actionUrl();
        }
    }
