### ISSUE TITLE
Redirct back error

### ISSUE THREAD

**Issue by MohamedSalahia** [asciisd/knet#13]
I want to know redirect back url is GET method or POST in both I have an error
`Route::get('knet/back', [\App\Http\Controllers\KnetPaymentController::class, 'showPaymentFormBack'])->name('payment.back');`
`'response_url' => '/knet/back',`

![Screenshot 2023-05-12 155904](https://github.com/asciisd/knet/assets/40516360/1c157e93-a087-426e-ae80-1a3f7702d39d)

When I do POST method:
`Route::post('knet/back', [\App\Http\Controllers\KnetPaymentController::class, 'showPaymentFormBack'])->name('payment.back');`
![Screenshot 2023-05-12 160122](https://github.com/asciisd/knet/assets/40516360/1b188a3b-496f-4e37-833a-cd99bf2f93ee)

**Comment by aemaddin** [comment]
Hello @mohamad19941994 

You can fix that by allowing the redirect backlink on your 
```shell
app/Http/Middleware/VerifyCsrfToken.php
``` 

![IMG_6166](https://github.com/asciisd/knet/assets/11630742/af3ee6bf-044f-44d9-9dee-6e756e3af974)
