### ISSUE TITLE
knet_transactions table

### ISSUE THREAD

**Issue by MohamedSalahia** [asciisd/knet#14]
Hello Amr,
I want ta ask you about knet_transactions table.
When I pay the payment process is completed on my account Knet dashboard.
But if see the table knet_transactions result=INITIATED and paymentid=NULL
![Screenshot 2023-05-16 080514](https://github.com/asciisd/knet/assets/40516360/409e9362-6770-4a72-8156-58c78f4836e7)
Is that payment right?
And I print my redirect back $request and  you can find paymentid but it's not stored in knet_transactions table:
![Screenshot 2023-05-16 080831](https://github.com/asciisd/knet/assets/40516360/26d58e3c-0ad8-4fe5-b2a7-eb1d8a6a3a0c)
Thank you so much Amr :)

**Comment by aemaddin** [comment]
Hello @mohamad19941994

Ok, let me describe how this package work after payment is completed,

After completing the process, the payment gateway redirects the user to success or error pages provided on the config file and .env file.

If you choose to use the default `response_url`, which is `/knet/response` and `/knet/error`, the package will handle that response and update the table with the status that comes from the gateway, but if you decide to change the URL, you should handle the response by yourself.

Last thing, please note that the`response_url` is to handle the response. If you want the user to go to another page after the handling, you can put a new env key, `KENT_REDIRECT_URL`, in the '.env' file to decide where to redirect after handling the response.

finally, you can find more about handling responses on `vendor/asciisd/knet/src/Http/Controllers/KnetController.php`
