### ISSUE TITLE
Calling (pay) method for none authenticated users

### ISSUE THREAD

**Issue by aqeelhashem** [asciisd/knet#4]
Hi,

I asked before about calling pay method , and you said :
" call it you should get user instance first"
https://github.com/asciisd/knet/issues/3

that's mean only the users which registered in my website can make a payments!

what if i want to create a form to let other people to pay a charge for something like (delivery charge) and i only want to save them addresses , and not to force them to registering in my website ?

thanks

**Comment by aemaddin** [comment]
Hi Aqeel,

you can use KPayManager class to do that, for example

```php
// make new payment
$knet = KPayManager::make(100, ['user_id' => $any_int_value]);

// make KnetTransaction record in your database
$payment = new Payment(
            KnetTransaction::create($knet->toArray())
        );

$payment->actionUrl(); // redirect user to pay with url generated
```

**Comment by aqeelhashem** [comment]
Thanks for reply,

 i was using 1.1 version so i should update (asciisd/knet ) to get  KPayManager class .

after calling (pay) method , the page has been transfered to knet page , but in (response) page i get this error:
```

Symfony\Component\Debug\Exception\FatalThrowableError
Class 'Asciisd\Knet\Http\Controllers\KnetResponseHandler' not found


Asciisd\Knet\Http\Controllers\KnetController::handleKnet
vendor/asciisd/knet/src/Http/Controllers/KnetController.php:39
```
on line :
`        $knetResponseHandler = new KnetResponseHandler();
`
it was working before in old version

i checked there is (use Asciisd\Knet\KPayResponseHandler;) in top of KnetController.php file

also i want to know how to add parameters with payment object like old code

```
payment = $user->pay($amount,[  
      'udf1' => $user->full_name,
        'udf2' => $user->family_name,
      ])

```

**Comment by aemaddin** [comment]
Can you please tell me which version you currently use?

**Comment by aqeelhashem** [comment]
"asciisd/knet": "^2.0",

**Comment by aemaddin** [comment]
If you upgraded to version 2 you can migrate using this link

https://github.com/asciisd/knet/blob/master/UPGRADE.md

**Comment by aqeelhashem** [comment]
should i delete these lines from KPayResponseStatus file:
```
 const CAPTURED = 'CAPTURED';
    const ABANDONED = 'ABANDONED';
    const CANCELLED = 'CANCELLED';
    const FAILED = 'FAILED';
    const DECLINED = 'DECLINED';
    const RESTRICTED = 'RESTRICTED';
    const VOID = 'VOID';
    const TIMEDOUT = 'TIMEDOUT';
    const UNKNOWN = 'UNKNOWN';
    const NOT_CAPTURED = 'NOT CAPTURED';
    const INITIATED = 'INITIATED';


    const SUCCESS_RESPONSES = ['CAPTURED'];
    const FAILED_RESPONSES = ['ABANDONED', 'CANCELLED', 'FAILED', 'DECLINED', 'RESTRICTED', 'VOID', 'TIMEDOUT', 'UNKNOWN', 'NOT CAPTURED'];
    const NEED_MORE_ACTION = ['INITIATED'];

```
 and replace it with these lines?:

```
 // strings
    KPayResponseStatus::CAPTURED;
    KPayResponseStatus::ABANDONED;
    KPayResponseStatus::CANCELLED;
    KPayResponseStatus::FAILED;
    KPayResponseStatus::DECLINED;
    KPayResponseStatus::RESTRICTED;
    KPayResponseStatus::VOID;
    KPayResponseStatus::TIMEDOUT;
    KPayResponseStatus::UNKNOWN;
    KPayResponseStatus::NOT_CAPTURED;
    KPayResponseStatus::INITIATED;

    // arrays
    KPayResponseStatus::SUCCESS_RESPONSES;
    KPayResponseStatus::FAILED_RESPONSES;
    KPayResponseStatus::NEED_MORE_ACTION;

```
if i do it i get syntax error

**Comment by aemaddin** [comment]
> should i delete these lines from KPayResponseStatus file:
> 
> ```
>  const CAPTURED = 'CAPTURED';
>     const ABANDONED = 'ABANDONED';
>     const CANCELLED = 'CANCELLED';
>     const FAILED = 'FAILED';
>     const DECLINED = 'DECLINED';
>     const RESTRICTED = 'RESTRICTED';
>     const VOID = 'VOID';
>     const TIMEDOUT = 'TIMEDOUT';
>     const UNKNOWN = 'UNKNOWN';
>     const NOT_CAPTURED = 'NOT CAPTURED';
>     const INITIATED = 'INITIATED';
> 
> 
>     const SUCCESS_RESPONSES = ['CAPTURED'];
>     const FAILED_RESPONSES = ['ABANDONED', 'CANCELLED', 'FAILED', 'DECLINED', 'RESTRICTED', 'VOID', 'TIMEDOUT', 'UNKNOWN', 'NOT CAPTURED'];
>     const NEED_MORE_ACTION = ['INITIATED'];
> ```
> 
> and replace it with these lines?:
> 
> ```
>  // strings
>     KPayResponseStatus::CAPTURED;
>     KPayResponseStatus::ABANDONED;
>     KPayResponseStatus::CANCELLED;
>     KPayResponseStatus::FAILED;
>     KPayResponseStatus::DECLINED;
>     KPayResponseStatus::RESTRICTED;
>     KPayResponseStatus::VOID;
>     KPayResponseStatus::TIMEDOUT;
>     KPayResponseStatus::UNKNOWN;
>     KPayResponseStatus::NOT_CAPTURED;
>     KPayResponseStatus::INITIATED;
> 
>     // arrays
>     KPayResponseStatus::SUCCESS_RESPONSES;
>     KPayResponseStatus::FAILED_RESPONSES;
>     KPayResponseStatus::NEED_MORE_ACTION;
> ```
> 
> if i do it i get syntax error

No it's just for clarify what is changes happened on the package, I am working to reproduce the error that you mentioned before and will back to you soon.

**Comment by aemaddin** [comment]
Ok, I've installed fresh version of Laravel and installed v1.1.17 then upgraded to the v2.0.0 and I am not able to reproduce the issue, can you please send me the log file to help me more to detect the problem.

Thanks

**Comment by aemaddin** [comment]
and please make sure to use the right APP_URL on .env file, also make sure to delete the old config file and use the new one.

**Comment by aqeelhashem** [comment]
sorry the mistake was from me , because i copy the old code in V1.1 to new one in (handleKnet) method

the old one is 
`$knetResponseHandler = new KnetResponseHandler();
`

but it must be:
`        $knetResponseHandler = new KPayResponseHandler();
`

remained last question:
how to add parameters with payment object
```
$payment = new Payment(
            KnetTransaction::create($knet->toArray())
        );
```

 like old code
```

payment = $user->pay($amount,[  
      'udf1' => $user->full_name,
        'udf2' => $user->family_name,
      ])
```

**Comment by aemaddin** [comment]
```php
// make new payment
$knet = KPayManager::make(100, [
        'user_id' => $any_int_value, 
        'udf1' => $user->full_name,
        'udf2' => $user->family_name
    ]);

// make KnetTransaction record in your database
$payment = new Payment(
            KnetTransaction::create($knet->toArray())
        );

$payment->actionUrl(); // redirect user to pay with url generated
```

**Comment by aqeelhashem** [comment]
Thanks very much ,
great work, 

good bless you

**Comment by aemaddin** [comment]
You’re welcome glad to help
