### ISSUE TITLE
The payment attempt failed because additional action is required before it can be completed.

### ISSUE THREAD

**Issue by sanu-basak** [asciisd/knet#5]
Unable to redirect to payment gateway page.

![Screenshot from 2020-11-30 22-18-10](https://user-images.githubusercontent.com/29189226/100638376-f591a180-3359-11eb-9e39-799aff2bd9b4.png)

**Comment by sanu-basak** [comment]
Please check & verify this issue

**Comment by aemaddin** [comment]
Hi Sanu,

this is normal behavior that allows you to differentiate between the finished transactions and the pending ones, so you can use try and catch to handle this,

for example:-

```php

try{
    $payment = $request->user()->pay($request->amount, [
        'udf1' => $request->user()->name,
        'udf2' => $request->user()->email
    ]);
} catch(\Asciisd\Knet\Exceptions\PaymentActionRequired $exception) {
    // do whatever you want with this 
    $payment = $exception->payment
} finally {
    // redirect user to payment url to complete the payment
    return $payment->actionUrl();
}

```

please note that you will find the payment object inside the PaymentActionRequired exception.

**Comment by sanu-basak** [comment]
yup..i got the object from catch block not try block...so this type of issue i'm facing.
Thanks a lot.

**Comment by sanu-basak** [comment]
Why otp is required..can you please check this.

**Comment by aemaddin** [comment]
OTP is applyed by the card issuer, api is not authorized to disable this feature
