### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Ahmad-Chebbo** [asciisd/knet#8]
Hello, I'm facing this error during the installation, how can I solve it, please?

![Capture](https://user-images.githubusercontent.com/41969693/124659580-ccb42a80-dead-11eb-8377-422c286f6a53.PNG)

**Comment by aemaddin** [comment]
Could you please provide more information about laravel version and steps to reproduce the problem

**Comment by aemaddin** [comment]
Fixed issue #8
