### ISSUE TITLE
(Error Code:Request_Resource_Not_Available)

### ISSUE THREAD

**Issue by alshugairi** [asciisd/knet#9]
![Selection_008](https://user-images.githubusercontent.com/16762929/154129615-473f3b00-2eb8-4754-9ce5-53034642bc32.jpg)

**Comment by aemaddin** [comment]
Thank you for your contribution, But can you please describe the problem so I can help with that.
Thanks

**Comment by aemaddin** [comment]
If you can provide me with steps to reproduce the problem, that will be great also.

**Comment by alshugairi** [comment]
I applied your steps, when I used buy function I have that error

**Comment by aemaddin** [comment]
Can you please show me a snap of your code?

**Comment by aemaddin** [comment]
Also, it's `pay`, not `buy`.

**Comment by alshugairi** [comment]
i copied your test code 
`try{
    $user = User::find(1);
    $payment = $user->pay(10);
    $payment->url; // this will return payment link
} catch(\Asciisd\Knet\Exceptions\PaymentActionRequired $exception) {
    return redirect($exception->payment->actionUrl());
}`

**Comment by alshugairi** [comment]
any update?

**Comment by aemaddin** [comment]
Please check for credentials and also if it's production credential then you should use SSL Certificate and disable Debug mode from .env file to accept the connection from KNet side
